// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

// export default sidebars;
export default {
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: '1. Власні ресурси',
      items: ['module01/intro','module01/base01'],
    },
        {
      type: 'category',
      label: '2. Ринок',
      items: ['module02/intro'],
    },
        {
      type: 'category',
      label: '3. Бізнес-модель',
      items: ['module03/intro'],
    },
        {
      type: 'category',
      label: '4. Продукт',
      items: ['module04/intro'],
    },
        {
      type: 'category',
      label: '5. Облік та фінанси',
      items: ['module05/intro'],
    },
        {
      type: 'category',
      label: '6. Оподаткування та документація',
      items: ['module06/intro'],
    },
        {
      type: 'category',
      label: '7. Юридичні питання та команда',
      items: ['module07/intro'],
    },
            {
      type: 'category',
      label: '8. Презентація продукту та компанії',
      items: ['module08/intro'],
    },
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
};
